window.WEDDING = {
  bride: "Thu Hà",
  groom: "Tuấn Anh",
  date: "2026-10-18",
  time: "17:00",
  ceremonyTime: "18:00",
  guest: "GĐ bác Mạnh - Nhung",
  venue: "Trung tâm tiệc cưới Sun Palace",
  address: "1111 đường Giải Phóng, Hoàng Mai, Hà Nội",
  brideParents: ["Nguyễn Văn Hưng", "Nguyễn Thị Phúc"],
  groomParents: ["Ngô Văn Điện", "Ngô Thị Vy"],
  brideAddress: "Số 5 ngõ 2 đường Bình Yên, Thường Tín, Hà Nội",
  groomAddress: "Số 9 ngách 156/21 Phương Liệt, phường Phương Liệt, Hà Nội",
  // Có thể dán liên kết Google Maps chính xác vào ba trường dưới đây.
  venueMapUrl: "https://maps.app.goo.gl/ina4r2x3y8wQHAYbA",
  groomMapUrl: "https://maps.app.goo.gl/cDYFQM7iXZ2YAcwr9",
  brideMapUrl: "https://maps.app.goo.gl/Lbedj6FZY1n9NP8n7",
  // Điền ảnh QR của bạn; để trống khi chưa có thông tin tài khoản.
  gifts: [
    { label: "Mừng cưới chú rể", qrImage: "assets/groom-qr.png", bank: "MSB", accountNumber: "8827021999", accountName: "NGO TUAN ANH" },
    { label: "Mừng cưới cô dâu", qrImage: "", bank: "", accountNumber: "", accountName: "" },
  ],
  rsvpEmail: "",
  music: "assets/wedding-song.mp3",
  musicYoutubeId: "",
  gallery: [
    "assets/T_T07748.JPG",
    "assets/T_T07829.JPG",
    "assets/T_T08068_1.JPG",
    "assets/T_T08145.JPG",
    "assets/T_T08337.JPG",
    "assets/T_T08438.JPG",
    "assets/T_T08506.JPG",
    "assets/T_T08623.JPG",
    "assets/T_T08762.jpg",
    "assets/T_T09055.JPG",
  ],
  timeline: [
    ["17:00", "Đón khách"],
    ["17:45", "Khai tiệc, phục vụ món ăn"],
    ["18:00", "Nghi lễ thành hôn"],
    ["20:00", "Kết thúc tiệc"],
  ],
};
